/* Generated by Streams Studio: November 30, 2016 at 10:33:19 AM EST */
package com.ibm.streamsx.watsonexplorer.operators;

import org.apache.log4j.Logger;

import com.ibm.streams.operator.OutputTuple;
import com.ibm.streams.operator.StreamingInput;
import com.ibm.streams.operator.StreamingOutput;
import com.ibm.streams.operator.Tuple;
import com.ibm.streams.operator.model.PrimitiveOperator;
import com.ibm.streamsx.watsonexplorer.RestParameters;
import com.ibm.streamsx.watsonexplorer.SearchResult;

@PrimitiveOperator(name = "Search", namespace = "com.ibm.streamsx.watsonexplorer", description = CASearchOperator.DESC)
public class CASearchOperator extends AbstractSearchOperator {
	
	private Logger logger = Logger.getLogger(CASearchOperator.class);
	
	@Override
	public final void process(StreamingInput<Tuple> inputStream, Tuple tuple) throws Exception {
		StreamingOutput<OutputTuple> outStream = getOutput(0);
		OutputTuple outTuple = outStream.newTuple();
		outTuple.assign(tuple);
		
		String query = queryAttr == null ? tuple.getString(DEFAULT_QUERY_ATTR_NAME) : queryAttr.getValue(tuple);
		logger.trace("query=" + query);

		RestParameters params = new RestParameters();
		params.put("query", query);
		
		if(!getOperatorContext().getParameterNames().contains("collectionName")) {
			addCollectionName(params, tuple);
		}
		
		SearchResult result = caClient.search(params);

		outTuple.setString(getResultAttrName(), result.getContent());
		outStream.submit(outTuple);
		
		while(result.hasMore()) {
			result = result.next();
			
			outTuple.setString(getResultAttrName(), result.getContent());
			outStream.submit(outTuple);
		}
	}
	
	static final String DESC = "This operator uses the Watson"
			+ " Explorer Content Analytics `/search` REST API to search for and return documents that satisfy the specified query."
			+ " The query to execute can be specified at compile-time by setting the **query** parameter, or can be specified dynamically"
			+ " while the application is running by specifying an input attribute via the **queryAttr** parameter.\\n\\n"
			+ " More information about the available parameters for this REST API can found in the Content Analytics REST API documentation in"
			+ " the Content Analytics installation directory: `<ES_INSTALL_PATH>/docs/api/rest/search`.";
}
