/* Generated by Streams Studio: November 30, 2016 at 10:33:19 AM EST */
package com.ibm.streams.watsonexplorer.operators;

import org.apache.log4j.Logger;

import com.ibm.streams.operator.OutputTuple;
import com.ibm.streams.operator.StreamingInput;
import com.ibm.streams.operator.StreamingOutput;
import com.ibm.streams.operator.Tuple;
import com.ibm.streams.operator.TupleAttribute;
import com.ibm.streams.operator.model.OutputPortSet;
import com.ibm.streams.operator.model.OutputPorts;
import com.ibm.streams.operator.model.Parameter;
import com.ibm.streams.operator.model.PrimitiveOperator;
import com.ibm.streams.operator.model.OutputPortSet.WindowPunctuationOutputMode;
import com.ibm.streams.watsonexplorer.RestParameters;
import com.ibm.streams.watsonexplorer.SearchResult;

@PrimitiveOperator(name = "SearchPreview", namespace = "com.ibm.streamsx.watsonexplorer", description = CASearchPreviewOperator.DESC)
public class CASearchPreviewOperator extends AbstractSearchOperator {
	
	private TupleAttribute<Tuple, String> uriAttr;
	
	private Logger logger = Logger.getLogger(CASearchPreviewOperator.class);

	@Parameter(optional = false, description = "Specifies the name of the input attribute that contains the document URI to be searched for.")
	public void setUriAttr(TupleAttribute<Tuple, String> uriAttr) {
		this.uriAttr = uriAttr;
	}
	
	public TupleAttribute<Tuple, String> getUriAttr() {
		return uriAttr;
	}
	
	@Override
	public void process(StreamingInput<Tuple> inputStream, Tuple tuple) throws Exception {
		StreamingOutput<OutputTuple> outStream = getOutput(0);
		OutputTuple outTuple = outStream.newTuple();
		outTuple.assign(tuple);
		
		String query = queryAttr == null ? tuple.getString(DEFAULT_QUERY_ATTR_NAME) : queryAttr.getValue(tuple);
		logger.trace("query=" + query);
		
		String uri = uriAttr.getValue(tuple);
		logger.trace("uri=" + uri);

		RestParameters params = new RestParameters();
		params.put("uri", uri);
		params.put("query", query);
		
		if(!getOperatorContext().getParameterNames().contains("collectionName")) {
			addCollectionName(params, tuple);
		}
		
		SearchResult result = caClient.searchPreview(params);

		outTuple.setString(getResultAttrName(), result.getContent());
		outStream.submit(outTuple);
		
		while(result.hasMore()) {
			result = result.next();
			
			outTuple.setString(getResultAttrName(), result.getContent());
			outStream.submit(outTuple);
		}
	}
	
	static final String DESC = "This operator uses the Watson"
			+ " Explorer Content Analytics `/search/preview` REST API to search for a specific document and return the contents of that document."
			+ " The document to search for should be specified dynamically at runtime using the **uriAttr** parameter.\\n\\n"
			+ " More information about the available parameters for this REST API can found in the Content Analytics REST API documentation in"
			+ " the Content Analytics installation directory: `<ES_INSTALL_PATH>/docs/api/rest/search`.";
}
